# Generated by Django 5.1.6 on 2025-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
