# Generated by Django 5.1.6 on 2025-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0002_alter_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
