# Generated by Django 5.1.6 on 2025-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(),
        ),
    ]
