name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Verify Railway CLI
        run: railway --version

      - name: Link to Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      # - name: Cleanup old deployments

      # - name: Create .env file

      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up --detach
